script:
  - "npm run travis"

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

env:
  matrix:
    - BLUEBIRD_VERSION=2
    - BLUEBIRD_VERSION=3

matrix:
  fast_finish: true
  include:
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
